In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [11]:
data = pd.read_csv('olympicmedal.csv',encoding = "ISO-8859-1")
data

City    Year      Sport       Discipline           Event  \
0      Montreal  1976.0   Aquatics           Diving  3m springboard   
1      Montreal  1976.0   Aquatics           Diving  3m springboard   
2      Montreal  1976.0   Aquatics           Diving  3m springboard   
3      Montreal  1976.0   Aquatics           Diving  3m springboard   
4      Montreal  1976.0   Aquatics           Diving    10m platform   
...         ...     ...        ...              ...             ...   
15428   Beijing  2008.0  Wrestling  Wrestling Gre-R       66 - 74kg   
15429   Beijing  2008.0  Wrestling  Wrestling Gre-R       66 - 74kg   
15430   Beijing  2008.0  Wrestling  Wrestling Gre-R       55 - 60kg   
15431   Beijing  2008.0  Wrestling  Wrestling Gre-R       60 - 66kg   
15432   Beijing  2008.0  Wrestling  Wrestling Gre-R      96 - 120kg   

                        Athlete Gender Country_Code        Country  \
0               KÖHLER, Christa  Women          GDR   East Germany   
1           KOSENKOV, Aleksandr    Men          URS   Soviet Union   
2          BOGGS, Philip George    Men          USA  United States   
3      CAGNOTTO, Giorgio Franco    Men          ITA          Italy   
4        WILSON, Deborah Keplar  Women          USA  United States   
...                         ...    ...          ...            ...   
15428        GUENOT, Christophe    Men          FRA         France   
15429       KVIRKELIA, Manuchar    Men          GEO        Georgia   
15430          RAHIMOV, Vitaliy    Men          AZE     Azerbaijan   
15431            GUENOT, Steeve    Men          FRA         France   
15432             LOPEZ, Mijain    Men          CUB           Cuba   

      Event_gender   Medal  
0                W  Silver  
1                M  Bronze  
2                M    Gold  
3                M  Silver  
4                W  Bronze  
...            ...     ...  
15428            M  Bronze  
15429            M    Gold  
15430            M  Silver  
15431            M    Gold  
15432            M    Gold  

[15433 rows x 11 columns]

In [18]:
df=data.drop(columns=['City','Discipline', 'Event', 'Athlete', 'Gender','Country','Event_gender'])
df['Medal'] = data['Medal'].map({"Bronze": 1, "Silver": 2, "Gold": 3})
df

Year      Sport Country_Code  Medal
0      1976.0   Aquatics          GDR    2.0
1      1976.0   Aquatics          URS    1.0
2      1976.0   Aquatics          USA    3.0
3      1976.0   Aquatics          ITA    2.0
4      1976.0   Aquatics          USA    1.0
...       ...        ...          ...    ...
15428  2008.0  Wrestling          FRA    1.0
15429  2008.0  Wrestling          GEO    3.0
15430  2008.0  Wrestling          AZE    2.0
15431  2008.0  Wrestling          FRA    3.0
15432  2008.0  Wrestling          CUB    3.0

[15433 rows x 4 columns]

In [101]:
#particular sport
df1=df.loc[(df['Sport']=='Aquatics')]
df2=df1.groupby(['Year','Country_Code'])['Medal'].count()

In [102]:
#Appearing more than 7 Olympics in the past
df2=df2.reset_index()
# df2.shape
df3=df2[df2['Country_Code'].isin(df2['Country_Code'].value_counts()[df2['Country_Code'].value_counts()>7].index)]
df3['Year'].unique()

array([1976., 1980., 1984., 1988., 1992., 1996., 2000., 2004., 2008.])

In [103]:
df3['Country_Code'].unique()

array(['AUS', 'CAN', 'GBR', 'HUN', 'ITA', 'NED', 'USA'], dtype=object)

In [145]:

df4=df3.groupby(['Country_Code','Year']).sum()
df4

Medal
Country_Code Year         
AUS          1976.0      1
             1980.0     10
             1984.0     18
             1988.0      3
             1992.0      9
             1996.0     25
             2000.0     63
             2004.0     40
             2008.0     70
CAN          1976.0     17
             1984.0     20
             1988.0     11
             1992.0      9
             1996.0     14
             2000.0     12
             2004.0      3
             2008.0      3
GBR          1976.0      6
             1980.0     11
             1984.0      8
             1988.0      3
             1992.0      1
             1996.0      2
             2004.0      4
             2008.0      6
HUN          1976.0     11
             1980.0     15
             1988.0      6
             1992.0      9
             1996.0      6
             2000.0     14
             2004.0     15
             2008.0     16
ITA          1976.0     13
             1980.0      1
             1988.0      1
             1992.0     15
             1996.0     14
             2000.0      6
             2004.0     20
             2008.0      2
NED          1976.0     13
             1980.0      4
             1984.0      9
             1988.0      4
             1996.0      2
             2000.0     16
             2004.0     15
             2008.0     20
USA          1976.0     51
             1984.0     73
             1988.0     57
             1992.0     62
             1996.0     72
             2000.0     80
             2004.0     89
             2008.0     94

In [146]:
df4=df4.reset_index()
df5=df4.loc[(df4['Country_Code']=='USA')]
df5


Country_Code    Year  Medal
49          USA  1976.0     51
50          USA  1984.0     73
51          USA  1988.0     57
52          USA  1992.0     62
53          USA  1996.0     72
54          USA  2000.0     80
55          USA  2004.0     89
56          USA  2008.0     94

In [149]:
reg=linear_model.LinearRegression()
reg.fit(df5[['Year']],df5.Medal)

LinearRegression()

In [151]:
reg.predict([[2020]])

array([105.62406015])

In [154]:
# AUS vs USA
df6=df4.loc[(df4['Country_Code']=='AUS')]
df6

Country_Code    Year  Medal
0          AUS  1976.0      1
1          AUS  1980.0     10
2          AUS  1984.0     18
3          AUS  1988.0      3
4          AUS  1992.0      9
5          AUS  1996.0     25
6          AUS  2000.0     63
7          AUS  2004.0     40
8          AUS  2008.0     70

In [155]:
reg.fit(df6[['Year']],df6.Medal)

LinearRegression()

In [156]:
reg.predict([[2020]])

array([82.32222222])

In [167]:
#total medals for USA, CHN, AUS

df10=df.groupby(['Country_Code','Year'])['Medal'].count()
df10=df10.reset_index()
df11=df10.loc[(df10['Country_Code']=='USA')]
df12=df10.loc[(df10['Country_Code']=='CHN')]
df13=df10.loc[(df10['Country_Code']=='AUS')]

In [169]:
#Predicted USA 2020 overall medal count
reg.fit(df11[['Year']],df11.Medal)
reg.predict([[2020]])

array([326.30827068])

In [170]:
#Predicted CHN 2020 overall medal count
reg.fit(df12[['Year']],df12.Medal)
reg.predict([[2020]])

array([183.14285714])

In [171]:
#Predicted AUS 2020 overall medal count
reg.fit(df13[['Year']],df13.Medal)
reg.predict([[2020]])

array([240.21666667])